apiVersion: apps/v1
kind: Deployment
metadata:
  name: chats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chats
  template:
    metadata:
      labels:
        app: chats
    spec:
      containers:
        - name: chats
          image: alexmelia41/chats
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ebarter
            - name: MONGO_URI
              value: 'mongodb://chats-mongo-srv:27017/chats'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: chats-srv
spec:
  selector:
    app: chats
  ports:
    - name: chats
      protocol: TCP
      port: 3000
      targetPort: 3000
##
