apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      containers:
        - name: trades
          image: alexmelia41/trades
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ebarter
            - name: MONGO_URI
              value: 'mongodb://trades-mongo-srv:27017/trades'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: trades-srv
spec:
  selector:
    app: trades
  ports:
    - name: trades
      protocol: TCP
      port: 3000
      targetPort: 3000
##
