name: deploy-items

on:
  push:
    branches:
      - master
    paths:
      - 'items/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd items && docker build -t alexmelia41/items .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push alexmelia41/items
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ebarter
      - run: kubectl rollout restart deployment items-depl
##
